import { Category, Tool } from '@/types/tool';

export const categories: Category[] = [
  { "slug": "math", "name": "Math", "icon": "calculator" },
  { "slug": "finance", "name": "Finance", "icon": "trending-up" },
  { "slug": "conversion", "name": "Conversion", "icon": "arrow-right-left" },
  { "slug": "geometry", "name": "Geometry", "icon": "shapes" },
  { "slug": "physics", "name": "Physics", "icon": "zap" },
  { "slug": "health", "name": "Health", "icon": "activity" },
  { "slug": "fun", "name": "Fun & Random", "icon": "dices" },
  { "slug": "datetime", "name": "Date & Time", "icon": "clock" }
];

export const tools: Tool[] = [
  { slug: "basic-calculator", name: "Basic Calculator", description: "Standard calculator with standard operations.", category: "math", component: "BasicCalculator" },
  { slug: "fractions-calculator", name: "Fractions Calculator", description: "Add, subtract, multiply, and divide fractions.", category: "math" },
  { slug: "quadratic-formula-calculator", name: "Quadratic Formula", description: "Calculate roots of a quadratic equation.", category: "math" },
  { slug: "square-root-calculator", name: "Square Root Calculator", description: "Calculate square roots and other roots.", category: "math" },
  { slug: "gpa-calculator", name: "GPA Calculator", description: "Calculate your Grade Point Average.", category: "math" },
  { slug: "percentage-change-calculator", name: "Percentage Change", description: "Calculate percentage increase or decrease.", category: "math" },
  { slug: "lcm-lcd-calculator", name: "LCM / LCD Calculator", description: "Find the Least Common Multiple/Denominator.", category: "math" },
  { slug: "mean-median-mode-calculator", name: "Mean, Median, Mode", description: "Calculate averages and central tendencies.", category: "math" },
  { slug: "standard-deviation-calculator", name: "Standard Deviation", description: "Calculate variance and standard deviation.", category: "math" },
  { slug: "long-division-calculator", name: "Long Division Calculator", description: "Calculate quotient and remainder.", category: "math" },
  { slug: "length-converter", name: "Length Converter", description: "Convert between various units of length.", category: "conversion" },
  { slug: "distance-converter", name: "Distance Conversion", description: "Convert between various units of distance.", category: "conversion" },
  { slug: "temperature-converter", name: "Temperature Conversion", description: "Convert between Celsius, Fahrenheit, and Kelvin.", category: "conversion" },
  { slug: "speed-converter", name: "Speed Conversion", description: "Convert between m/s, km/h, mph, knots, etc.", category: "conversion" },
  { slug: "weight-converter", name: "Weight Converter", description: "Convert between various units of weight and mass.", category: "conversion" },
  { slug: "volume-converter", name: "Volume Converter", description: "Convert between various units of volume.", category: "conversion" },
  { slug: "area-of-circle", name: "Area of Circle", description: "Calculate the area and circumference of a circle.", category: "geometry" },
  { slug: "area-of-rectangle", name: "Area of Rectangle", description: "Calculate the area and perimeter of a rectangle.", category: "geometry" },
  { slug: "area-of-triangle", name: "Area of Triangle", description: "Calculate the area of a triangle.", category: "geometry" },
  { slug: "area-of-square", name: "Area of Square", description: "Calculate the area and perimeter of a square.", category: "geometry" },
  { slug: "volume-of-cube", name: "Volume of Cube", description: "Calculate the volume of a cube.", category: "geometry" },
  { slug: "volume-of-sphere", name: "Volume of Sphere", description: "Calculate the volume of a sphere.", category: "geometry" },
  { slug: "volume-of-cylinder", name: "Volume of Cylinder", description: "Calculate the volume of a cylinder.", category: "geometry" },
  { slug: "pythagorean-theorem", name: "Pythagorean Theorem", description: "Calculate the hypotenuse of a right-angled triangle.", category: "geometry" },
  { slug: "velocity", name: "Velocity Calculator", description: "Calculate velocity from distance and time.", category: "physics" },
  { slug: "kinetic-energy", name: "Kinetic Energy", description: "Calculate kinetic energy from mass and velocity.", category: "physics" },
  { slug: "ohms-law-calculator", name: "Ohm's Law", description: "Calculate voltage from current and resistance.", category: "physics" },
  { slug: "speed-calculator", name: "Speed Calculator", description: "Calculate speed from distance and time.", category: "physics" },
  { slug: "density-calculator", name: "Density Calculator", description: "Calculate density from mass and volume.", category: "physics" },
  { slug: "simple-interest-calculator", name: "Simple Interest", description: "Calculate simple interest earned.", category: "finance" },
  { slug: "markup-calculator", name: "Markup Calculator", description: "Calculate profit and markup percentage.", category: "finance" },
  { slug: "sip-calculator", name: "SIP Calculator", description: "Calculate SIP and Lumpsum investment returns.", category: "finance" },
  { slug: "mortgage-calculator", name: "Mortgage Calculator", description: "Calculate monthly mortgage payments.", category: "finance" },
  { slug: "emi-calculator", name: "EMI Calculator", description: "Calculate Equated Monthly Installment for loans.", category: "finance" },
  { slug: "compound-interest-calculator", name: "Compound Interest", description: "Calculate compound interest over time.", category: "finance" },
  { slug: "car-loan-calculator", name: "Car Loan Calculator", description: "Calculate car loan payments.", category: "finance" },
  { slug: "sales-tax-calculator", name: "Sales Tax Calculator", description: "Calculate sales tax on purchases.", category: "finance" },
  { slug: "discount-calculator", name: "Discount Calculator", description: "Calculate discounts on prices.", category: "finance" },
  { slug: "percentage-calculator", name: "Percentage Calculator", description: "Calculate percentages of numbers.", category: "finance" },
  { slug: "savings-calculator", name: "Savings Calculator", description: "Calculate savings growth over time.", category: "finance" },
  { slug: "retirement-savings-calculator", name: "Retirement Savings", description: "Calculate retirement savings projection.", category: "finance" },
  { slug: "currency-converter", name: "Currency Converter", description: "Convert between currencies with live rates.", category: "finance" },
  { slug: "bmi-calculator", name: "BMI Calculator", description: "Calculate your Body Mass Index.", category: "health" },
  { slug: "age-calculator", name: "Age Calculator", description: "Calculate your exact age in years, months, and days.", category: "datetime" },
  { slug: "date-difference-calculator", name: "Date Difference Calculator", description: "Calculate the exact difference between two dates.", category: "datetime" },
  { slug: "countdown-timer", name: "Countdown Timer", description: "A simple countdown timer.", category: "datetime", component: "CountdownTimer" },
  { slug: "time-calculator", name: "Time Calculator", description: "Add or subtract time.", category: "datetime" },
  { slug: "military-time-converter", name: "Military Time Converter", description: "Convert between 12-hour and 24-hour formats.", category: "datetime" },
  { slug: "calorie-calculator", name: "Calorie & Target HR", description: "Calculate daily calorie needs and target heart rate.", category: "health" },
  { slug: "pregnancy-calculator", name: "Pregnancy Calculator", description: "Calculate estimated due date and current week of pregnancy.", category: "health" },
  { slug: "height-converter", name: "Height Converter", description: "Convert between centimeters and feet/inches.", category: "conversion" },
  { slug: "random-number-generator", name: "Random Number Generator", description: "Generate a random number between a range.", category: "fun" },
  { slug: "password-generator", name: "Password Generator", description: "Generate a secure random password.", category: "fun" },
  { slug: "dice-roller", name: "Dice Roller", description: "Roll one or more virtual dice.", category: "fun", component: "DiceRoller" },
  { slug: "coin-flipper", name: "Coin Flipper", description: "Flip a virtual coin multiple times.", category: "fun", component: "CoinFlipper" },
  { slug: "lottery-number-generator", name: "Lottery Number Generator", description: "Generate random numbers for lottery tickets.", category: "fun", component: "LotteryMachine" }
];
