import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service | MathCalc",
  description: "Read the Terms of Service for using MathCalc's free online calculators.",
};

export default function TermsPage() {
  return (
    <div className="container mx-auto px-4 py-12 md:py-16 max-w-4xl">
      <div className="space-y-8 bg-background/60 backdrop-blur-xl border border-foreground/20 rounded-[2rem] p-8 md:p-12 shadow-2xl">
        <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight text-foreground">
          Terms of <span className="text-primary">Service</span>
        </h1>
        <div className="prose prose-lg dark:prose-invert max-w-none text-muted-foreground leading-relaxed">
          <p><strong>Effective Date:</strong> {new Date().toLocaleDateString()}</p>
          <p>
            Welcome to MathCalc. By accessing or using our multipage web application and its suite of free online calculators, you agree to comply with and be bound by the following Terms of Service.
          </p>
          <h2>1. Use of Our Tools</h2>
          <p>
            All calculators, generators, and tools provided on MathCalc are intended solely for general informational and educational purposes. While we employ rigorous testing to ensure mathematical accuracy, we make no absolute guarantees regarding the correctness, reliability, or completeness of any calculation.
          </p>
          <h2>2. No Professional Advice</h2>
          <p>
            The results generated by our tools (especially those within the Finance and Health categories) <strong>do not constitute professional advice</strong>. 
            You should not make critical financial, legal, medical, or engineering decisions based solely on the output of MathCalc. Always consult with a certified professional (such as a doctor or financial advisor) before taking action.
          </p>
          <h2>3. Intellectual Property</h2>
          <p>
            The design, source code, logos, and original text of MathCalc are protected by copyright and intellectual property laws. You may not scrape, clone, or redistribute our tools without explicit written permission.
          </p>
          <h2>4. Limitation of Liability</h2>
          <p>
            Under no circumstances shall MathCalc or its developers be held liable for any direct, indirect, incidental, special, or consequential damages resulting from the use or inability to use our website.
          </p>
          <h2>5. Updates to Terms</h2>
          <p>
            We may update these terms at our discretion. Continued use of MathCalc following any changes indicates your acceptance of the new terms.
          </p>
        </div>
      </div>
    </div>
  );
}
